# Generated by Django 5.1.7 on 2025-03-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripwise', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='driver',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='driver',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
