# Generated by Django 5.1.7 on 2025-03-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripwise', '0002_remove_driver_company_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daily_logs', models.JSONField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('rest_stops', models.JSONField()),
                ('route_data', models.JSONField()),
                ('trip_details', models.JSONField()),
            ],
        ),
    ]
